import { GoogleGenAI, Modality } from "@google/genai";
import { GeneratedImage } from "../types";

// Initialize the Gemini API client
// The API key is guaranteed to be in process.env.API_KEY
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

/**
 * Edits an image or generates a new one based on a text prompt.
 * Uses 'gemini-2.5-flash-image' (Nano Banana).
 *
 * @param prompt The text description of the edit or image to generate.
 * @param base64Image Optional. The base64 encoded image data to edit.
 * @param mimeType Optional. The mime type of the input image (e.g., 'image/png').
 */
export const processImageRequest = async (
  prompt: string,
  base64Image?: string,
  mimeType: string = 'image/png'
): Promise<GeneratedImage> => {
  try {
    const model = 'gemini-2.5-flash-image';
    
    const parts: any[] = [];

    // If an image is provided, we are in "Edit" mode (or image-guided generation)
    if (base64Image) {
      // Strip header if present (e.g., "data:image/png;base64,")
      const cleanBase64 = base64Image.includes('base64,') 
        ? base64Image.split('base64,')[1] 
        : base64Image;

      parts.push({
        inlineData: {
          data: cleanBase64,
          mimeType: mimeType,
        },
      });
    }

    // Add the text prompt
    parts.push({
      text: prompt,
    });

    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: parts,
      },
      config: {
        // Critical for image generation/editing models
        responseModalities: [Modality.IMAGE],
      },
    });

    // Extract the image from the response
    // The model returns the image in the inlineData of the first part of the first candidate
    const candidates = response.candidates;
    if (candidates && candidates.length > 0) {
      const content = candidates[0].content;
      if (content && content.parts && content.parts.length > 0) {
        // Find the part that contains inlineData (the image)
        const imagePart = content.parts.find((p) => p.inlineData);
        
        if (imagePart && imagePart.inlineData) {
          return {
            data: imagePart.inlineData.data,
            mimeType: imagePart.inlineData.mimeType || 'image/png',
          };
        }
      }
    }

    throw new Error("No image was generated by the model.");

  } catch (error: any) {
    console.error("Gemini API Error:", error);
    throw new Error(error.message || "Failed to process image request.");
  }
};
